// game
export const START_GAME = 'START_GAME';
export const FINISH_GAME = 'FINISH_GAME';
export const WRITE_LETTER = 'WRITE_LETTER';
export const CHANGE_CURRENT_INDEX = 'CHANGE_CURRENT_INDEX';
export const COLLECT_ERRORS = 'COLLECT_ERRORS';
export const CHANGE_TIME = 'CHANGE_TIME';

// fetch text
export const GET_TEXT_INIT = 'GET_TEXT_INIT';
export const GET_TEXT_START = 'GET_TEXT_START';
export const GET_TEXT_SUCCESS = 'GET_TEXT_SUCCESS';
export const GET_TEXT_FAIL = 'GET_TEXT_FAIL';

// fetch history
export const GET_HISTORY_INIT = 'GET_HISTORY_INIT';
export const GET_HISTORY_START = 'GET_HISTORY_START';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAIL = 'GET_HISTORY_FAIL';

// create history
export const CREATE_HISTORY_INIT = 'CREATE_HISTORY_INIT';
export const CREATE_HISTORY_START = 'CREATE_HISTORY_START';
export const CREATE_HISTORY_SUCCESS = 'CREATE_HISTORY_SUCCESS';
export const CREATE_HISTORY_FAIL = 'CREATE_HISTORY_FAIL';